// ==========================================
// 🎯 4. 주간 도전 과제 (26종 챌린지 전체 데이터베이스)
// ==========================================

const WEEKLY_CHALLENGES = [
    {
        id: 1,
        title: "1. The Mind's Eye (심안 / 마음의 눈)",
        nameKr: "심안 (마음의 눈)",
        nameEn: "The Mind's Eye",
        map: "Grafton Farmhouse (그라프톤 농가)",
        evidences: "3개 (모든 증거 정상 제공)",
        setupTime: "0초 (즉시 사냥 가능)",
        sanity: "시작 100% / 감소율 100%",
        speed: "플레이어 100% / 유령 100%",
        hiding: "보통 (일부 차단)",
        breaker: "꺼진 상태로 시작 (위치 미표시)",
        weather: "안개 (Fog)",
        items: "🚫 손전등류 / 헤드기어 전면 차단<br>📦 비디오 카메라, 삼각대, 양초, 라이터, 7종 증거 수집 장비 풀세트 지급",
        strategy: "손전등이 아예 없으므로 <strong>비디오 카메라 야간 투시 화면을 보면서 실내를 이동</strong>해야 합니다. 고스트 룸을 찾은 후 삼각대에 비디오 카메라를 세우고 트럭에서 D.O.T.S.와 오브, 책 등을 안전하게 확인하세요. 복도 바닥에 양초를 켜두면 사냥 시 안전한 도주로가 확보됩니다."
    },
    {
        id: 2,
        title: "2. Gotta Go Fast (패스트 앤 퓨리어스)",
        nameKr: "패스트 앤 퓨리어스",
        nameEn: "Gotta Go Fast",
        map: "Camp Woodwind (우드윈드 캠프장)",
        evidences: "3개",
        setupTime: "0초",
        sanity: "시작 100% / 감소율 100%",
        speed: "플레이어 150% (무한 달리기) / 유령 150%",
        hiding: "매우 적음",
        breaker: "꺼진 상태",
        weather: "맑음",
        items: "📦 3티어 고속 탐색 장비 풀세트 지급",
        strategy: "플레이어와 유령 모두 1.5배로 매우 빠릅니다. 우드윈드 캠프장의 테이블이나 텐트 주변을 넓게 돌며 루핑할 수 있지만, 유령의 시야 가속이 붙으면 순식간에 잡히므로 정화향초를 필수로 지참하세요."
    },
    {
        id: 3,
        title: "3. Audio Only (오디오 전용)",
        nameKr: "오디오 전용",
        nameEn: "Audio Only",
        map: "Maple Lodge Campsite (메이플 롯지)",
        evidences: "3개",
        setupTime: "0초",
        sanity: "시작 100%",
        speed: "표준 100%",
        hiding: "보통",
        breaker: "꺼진 상태",
        weather: "비 (Rain)",
        items: "🚫 손전등, 비디오 카메라 미지급<br>📦 지향성 마이크, 사운드 센서, 소금, 사운드 레코더 지급",
        strategy: "시각적 조명 도구가 극도로 제한됩니다. 지향성 마이크와 사운드 센서를 롯지 구역마다 배치하고 트럭과 현장에서 소리 수치를 모니터링하여 유령 위치를 좁혀야 합니다."
    },
    {
        id: 4,
        title: "4. Hide and Seek: Extreme (숨바꼭질: 익스트림)",
        nameKr: "숨바꼭질: 익스트림",
        nameEn: "Hide and Seek: Extreme",
        map: "6 Tanglewood Drive (탱글우드)",
        evidences: "3개",
        setupTime: "0초",
        sanity: "시작 0% (즉시 사냥 돌입)",
        speed: "표준 100%",
        hiding: "<strong>모든 공식 은신처 100% 차단</strong>",
        breaker: "꺼진 상태",
        weather: "강풍",
        items: "📦 십자가, 정화향초, 안정제 다수 지급",
        strategy: "시작하자마자 정신력이 0%이므로 즉시 안정제를 먹거나 십자가를 방안에 깔아야 합니다. 은신처가 전무하므로 거실 가구나 주방 아일랜드 식탁 동선을 활용해 유령을 드리블해야 합니다."
    },
    {
        id: 5,
        title: "5. Apocalypse Lite (아포칼립스 라이트)",
        nameKr: "아포칼립스 라이트",
        nameEn: "Apocalypse Lite",
        map: "Sunny Meadows (써니 메도우 본관)",
        evidences: "<strong>0개 (증거 미제공)</strong>",
        setupTime: "0초",
        sanity: "시작 0% (안정제 없음)",
        speed: "플레이어 100% / 유령 150%",
        hiding: "없음",
        breaker: "영구 고장",
        weather: "폭풍우",
        items: "📦 1티어 기본 장비 세트",
        strategy: "증거가 나오지 않으므로 오직 유령의 발소리 템포, 헌팅 깜빡임 주기, 특수 능력(데오겐의 감속, 데몬의 즉시 헌팅, 레이스의 소금 반응 등)만으로 유령을 특정해야 합니다."
    },
    {
        id: 6,
        title: "6. Survival Training (생존 훈련)",
        nameKr: "생존 훈련",
        nameEn: "Survival Training",
        map: "42 Edgefield Road (엣지필드)",
        evidences: "3개",
        setupTime: "0초",
        sanity: "시작 100%",
        speed: "표준 100%",
        hiding: "매우 적음",
        breaker: "꺼진 상태",
        weather: "안개",
        items: "🚫 십자가, 정화향초, 소금 등 모든 방어 아이템 차단<br>📦 순수 조사 장비만 지급",
        strategy: "유령의 사냥을 물리적으로 저지하거나 실명시킬 수단이 전혀 없습니다. 불을 최대한 켜서 정신력을 50% 이상으로 유지하고, 사냥이 터지면 2층 옷장이나 지하 구석으로 즉시 숨어야 합니다."
    },
    {
        id: 7,
        title: "7. Speedrun (스피드런)",
        nameKr: "스피드런",
        nameEn: "Speedrun",
        map: "10 Ridgeview Court (리지뷰)",
        evidences: "3개",
        setupTime: "30초",
        sanity: "시작 100%",
        speed: "표준 100%",
        hiding: "보통",
        breaker: "켜진 상태",
        weather: "맑음",
        items: "📦 3티어 최상급 탐색 장비 지급",
        strategy: "30초의 짧은 준비 시간 내에 3티어 온도계와 EMF로 고스트 룸을 즉시 찾아내고 증거 3개를 신속하게 등록하고 탈출해야 하는 타임어택형 챌린지입니다."
    },
    {
        id: 8,
        title: "8. Slow and Steady (느림의 미학)",
        nameKr: "느림의 미학",
        nameEn: "Slow and Steady",
        map: "Bleasdale Farmhouse (블리즈데일 농가)",
        evidences: "3개",
        setupTime: "0초",
        sanity: "시작 100%",
        speed: "플레이어 50% (달리기 불가) / 유령 50%",
        hiding: "많음",
        breaker: "꺼진 상태",
        weather: "눈 (Snow)",
        items: "📦 표준 장비 세트 지급",
        strategy: "플레이어와 유령 모두 반토막 속도로 움직입니다. 유령이 기어가듯 다가오므로 침착하게 거리를 벌릴 수 있지만, 멀리 도망치는 데도 시간이 오래 걸리므로 가까운 은신처를 미리 봐두세요."
    },
    {
        id: 9,
        title: "9. Paranormal Photography (심령사진 마스터)",
        nameKr: "심령사진 마스터",
        nameEn: "Paranormal Photography",
        map: "13 Belleview Street (벨뷰)",
        evidences: "3개",
        setupTime: "0초",
        sanity: "시작 100%",
        speed: "표준 100%",
        hiding: "보통",
        breaker: "꺼진 상태",
        weather: "맑음",
        items: "📦 3티어 포토 카메라 & 삼각대 풀세트 지급",
        strategy: "사진 촬영 보조 장비가 풍족하게 제공됩니다. 유령 이벤트나 D.O.T.S. 통과 실루엣, 뼈, 상호작용 지문을 적극적으로 촬영해 앨범을 채우며 조사하세요."
    },
    {
        id: 10,
        title: "10. Lights Out (암흑천지 / 정전)",
        nameKr: "암흑천지 (정전)",
        nameEn: "Lights Out",
        map: "Willow Street (윌로우)",
        evidences: "3개",
        setupTime: "0초",
        sanity: "시작 100%",
        speed: "표준 100%",
        hiding: "보통",
        breaker: "<strong>영구 고장 (복구 불가)</strong>",
        weather: "폭풍우",
        items: "📦 손전등, 3티어 양초, 라이터 대량 지급",
        strategy: "집안 전등을 절대 켤 수 없으므로 양초를 집안 곳곳에 배치해 안전 구역을 만들어야 합니다. 매어(Mare)의 공격성이 극대화되는 조건이므로 빠른 증거 확보가 관건입니다."
    },
    {
        id: 11,
        title: "11. Vampire Hunter (뱀파이어 헌터)",
        nameKr: "뱀파이어 헌터",
        nameEn: "Vampire Hunter",
        map: "Point Hope (포인트 호프 등대)",
        evidences: "3개",
        setupTime: "0초",
        sanity: "시작 100%",
        speed: "표준 100%",
        hiding: "보통",
        breaker: "꺼진 상태",
        weather: "안개",
        items: "📦 UV 라이트, 양초, 말뚝형 장비 세트 지급",
        strategy: "나선형 계단 구조를 오르내리며 층별 온도와 UV 반응을 확인해야 합니다. 좁은 계단에서 사냥이 터지면 도주가 어렵기 때문에 십자가를 층계참에 배치하세요."
    },
    {
        id: 12,
        title: "12. Deafening Silence (적막의 공포)",
        nameKr: "적막의 공포",
        nameEn: "Deafening Silence",
        map: "Prison (교도소)",
        evidences: "3개",
        setupTime: "0초",
        sanity: "시작 100%",
        speed: "표준 100%",
        hiding: "보통",
        breaker: "꺼진 상태",
        weather: "맑음",
        items: "🚫 글로벌 무전기 사용 불가<br>📦 사운드 센서, 모션 센서 지급",
        strategy: "무전기를 통한 원거리 팀원 브리핑이 불가능합니다. 넓은 교도소 A/B동을 수색할 때 사운드 센서를 설치해 트럭에서 소리 반응 구역을 찾아 진입하세요."
    },
    {
        id: 13,
        title: "13. Glow in the Dark (야광의 밤)",
        nameKr: "야광의 밤",
        nameEn: "Glow in the Dark",
        map: "Camp Woodwind (우드윈드 캠프장)",
        evidences: "3개",
        setupTime: "0초",
        sanity: "시작 100%",
        speed: "표준 100%",
        hiding: "보통",
        breaker: "꺼진 상태",
        weather: "달밤",
        items: "🚫 일반 손전등 미지급<br>📦 1티어 화학 형광봉, UV 랜턴 대량 지급",
        strategy: "손전등 대신 형광봉을 흔들어 바닥에 던져 길을 밝혀야 합니다. 형광봉은 비전자기기이므로 헌팅 중 손에 쥐고 있어도 유령에게 위치가 노출되지 않는 이점이 있습니다."
    },
    {
        id: 14,
        title: "14. Back to Basics (초심으로)",
        nameKr: "초심으로",
        nameEn: "Back to Basics",
        map: "6 Tanglewood Drive (탱글우드)",
        evidences: "3개",
        setupTime: "0초",
        sanity: "시작 100%",
        speed: "표준 100%",
        hiding: "많음",
        breaker: "꺼진 상태",
        weather: "맑음",
        items: "📦 <strong>오직 1티어 구형 기본 장비만 지급</strong>",
        strategy: "아날로그 바늘 EMF, 수은 온도계, 찢어진 노트 등 1티어 기본 장비만 주어집니다. 장비 스펙은 낮지만 증거가 3개 모두 나오므로 기본에 충실하게 플레이하면 쉽게 클리어 가능합니다."
    },
    {
        id: 15,
        title: "15. Detective Work (명탐정 코난)",
        nameKr: "명탐정 코난",
        nameEn: "Detective Work",
        map: "42 Edgefield Road (엣지필드)",
        evidences: "<strong>2개 (증거 1개 숨김)</strong>",
        setupTime: "0초",
        sanity: "시작 100%",
        speed: "표준 100%",
        hiding: "보통",
        breaker: "꺼진 상태",
        weather: "비",
        items: "📦 2티어 표준 장비 세트",
        strategy: "증거가 2개까지만 나오므로, 2개 증거 조합으로 좁혀진 유령 후보군 중에서 발소리 속도, 특수 행동, 향초 반응 시간 등을 대조해 최종 유령을 추리해야 합니다."
    },
    {
        id: 16,
        title: "16. The Hunchback (곱추의 저주)",
        nameKr: "곱추의 저주",
        nameEn: "The Hunchback",
        map: "Grafton Farmhouse (그라프톤 농가)",
        evidences: "3개",
        setupTime: "0초",
        sanity: "시작 100%",
        speed: "플레이어 이동속도 75% (감소)",
        hiding: "보통",
        breaker: "꺼진 상태",
        weather: "안개",
        items: "📦 표준 장비 세트",
        strategy: "플레이어의 이동 속도가 다소 느려 유령에게 쫓길 때 도주가 어렵습니다. 방 입구마다 십자가를 꼼꼼히 깔고 정화향초를 반드시 손에 쥐고 다니세요."
    },
    {
        id: 17,
        title: "17. Primitive Defense (원시적 방어)",
        nameKr: "원시적 방어",
        nameEn: "Primitive Defense",
        map: "Bleasdale Farmhouse (블리즈데일 농가)",
        evidences: "3개",
        setupTime: "0초",
        sanity: "시작 100%",
        speed: "표준 100%",
        hiding: "보통",
        breaker: "꺼진 상태",
        weather: "바람",
        items: "🚫 전자 센서 및 모니터 장비 제한<br>📦 양초, 소금, 십자가, 라이팅북 등 아날로그 장비 중심",
        strategy: "전자 센서 대신 바닥에 소금을 촘촘히 뿌리고 양초 불빛을 활용해 유령의 배회 동선과 방 위치를 특정해야 합니다."
    },
    {
        id: 18,
        title: "18. Sanity Drain (멘탈 붕괴)",
        nameKr: "멘탈 붕괴",
        nameEn: "Sanity Drain",
        map: "High School (고등학교)",
        evidences: "3개",
        setupTime: "0초",
        sanity: "시작 100% / <strong>정신력 감소율 200% (초고속)</strong>",
        speed: "표준 100%",
        hiding: "많음",
        breaker: "꺼진 상태",
        weather: "맑음",
        items: "📦 안정제 풀세트, 양초, 손전등 지급",
        strategy: "어둠 속에 서 있으면 정신력이 순식간에 0%로 바닥납니다. 넓은 고등학교 복도 전등을 빠르게 켜면서 이동하고, 안정제를 아끼지 말고 주기적으로 복용하세요."
    },
    {
        id: 19,
        title: "19. Tag! You're It! (술래잡기)",
        nameKr: "술래잡기",
        nameEn: "Tag! You're It!",
        map: "Sunny Meadows Restricted (써니 메도우 구역제한)",
        evidences: "3개",
        setupTime: "0초",
        sanity: "시작 0%",
        speed: "플레이어 150% / 유령 150%",
        hiding: "적음",
        breaker: "꺼진 상태",
        weather: "안개",
        items: "📦 정화향초, 십자가, 3티어 증거 장비",
        strategy: "좁은 구역에서 빠른 속도의 유령과 숨바꼭질을 벌여야 합니다. 구역 내 방 문을 열어두어 막다른 길에 갇히지 않도록 퇴로를 확보하세요."
    },
    {
        id: 20,
        title: "20. Flash Mob (플래시 몹)",
        nameKr: "플래시 몹",
        nameEn: "Flash Mob",
        map: "Maple Lodge Campsite (메이플 롯지)",
        evidences: "3개",
        setupTime: "0초",
        sanity: "시작 100%",
        speed: "표준 100%",
        hiding: "보통",
        breaker: "켜진 상태",
        weather: "맑음",
        items: "📦 <strong>3티어 초고광량 프로 손전등 풀세트 지급</strong>",
        strategy: "최고급 손전등이 대량 지급되어 야외 시야 확보가 매우 쾌적합니다. 다만 유령의 상호작용 빈도가 높으니 물건 던지기와 EMF 반응을 빠르게 캐치하세요."
    },
    {
        id: 21,
        title: "21. Technophobia (기계 공포증)",
        nameKr: "기계 공포증",
        nameEn: "Technophobia",
        map: "10 Ridgeview Court (리지뷰)",
        evidences: "3개",
        setupTime: "0초",
        sanity: "시작 100%",
        speed: "표준 100%",
        hiding: "보통",
        breaker: "영구 고장",
        weather: "비",
        items: "🚫 전자식 계측기 전면 차단<br>📦 수은 온도계, 라이팅북, 양초, UV 형광봉 지급",
        strategy: "전자기기가 없으므로 라이주에게 속도 버프를 줄 위험이 전혀 없습니다. 수은 온도계와 형광봉, 노트 필기로 안전하게 3가지 증거를 수집하세요."
    },
    {
        id: 22,
        title: "22. Item Roulette (아이템 룰렛)",
        nameKr: "아이템 룰렛",
        nameEn: "Item Roulette",
        map: "Willow Street (윌로우)",
        evidences: "3개",
        setupTime: "0초",
        sanity: "시작 100%",
        speed: "표준 100%",
        hiding: "보통",
        breaker: "꺼진 상태",
        weather: "바람",
        items: "📦 무작위로 구성된 무작위 장비 세트 지급",
        strategy: "트럭에 어떤 장비가 들어있는지 먼저 확인한 뒤, 주어진 한정된 도구에 맞춰 증거 수집 우선순위를 유연하게 정해야 합니다."
    },
    {
        id: 23,
        title: "23. Cold Day in Hell (혹한기 훈련)",
        nameKr: "혹한기 훈련",
        nameEn: "Cold Day in Hell",
        map: "Bleasdale Farmhouse (블리즈데일)",
        evidences: "3개",
        setupTime: "0초",
        sanity: "시작 100%",
        speed: "표준 100%",
        hiding: "보통",
        breaker: "꺼진 상태",
        weather: "<strong>폭설 (Heavy Snow)</strong>",
        items: "📦 표준 장비 및 3티어 온도계 지급",
        strategy: "날씨가 눈보라라 집안 전체 기본 온도가 1~3°C까지 매우 낮습니다. 입김만 보고 서늘함으로 착각하지 말고 반드시 온도계가 <strong>0°C 미만 (영하)</strong>으로 떨어지는지 확인하세요."
    },
    {
        id: 24,
        title: "24. Mirror, Mirror (거울아 거울아)",
        nameKr: "거울아 거울아",
        nameEn: "Mirror, Mirror",
        map: "13 Belleview Street (벨뷰)",
        evidences: "3개",
        setupTime: "0초",
        sanity: "시작 100%",
        speed: "표준 100%",
        hiding: "보통",
        breaker: "꺼진 상태",
        weather: "맑음",
        items: "📦 저주받은 물건: <strong>유령의 거울 (Haunted Mirror) 상시 스폰</strong>",
        strategy: "집안에 스폰된 유령의 거울을 들고 우클릭하여 고스트 룸의 풍경을 즉시 확인하세요. 거울을 오래 보면 정신력이 급락해 저주 사냥이 터지므로 1초만 보고 바로 끄는 것이 핵심입니다."
    },
    {
        id: 25,
        title: "25. Phantom of the High School (고등학교의 유령)",
        nameKr: "고등학교의 유령",
        nameEn: "Phantom of the High School",
        map: "High School (고등학교)",
        evidences: "3개",
        setupTime: "0초",
        sanity: "시작 100%",
        speed: "표준 100%",
        hiding: "많음",
        breaker: "꺼진 상태",
        weather: "안개",
        items: "📦 지향성 마이크, 사운드 센서, 온도계 풀세트",
        strategy: "넓은 복도를 수색하기 위해 지향성 마이크를 들고 소리 방향을 체크하거나, 1층/2층 복도 문들이 열려 있는지 확인하며 유령의 교실을 좁혀가세요."
    },
    {
        id: 26,
        title: "26. The Unknown (미지의 존재)",
        nameKr: "미지의 존재",
        nameEn: "The Unknown",
        map: "Point Hope (포인트 호프 등대)",
        evidences: "<strong>0~1개 제한 (극한 추리)</strong>",
        setupTime: "0초",
        sanity: "시작 100%",
        speed: "표준 100%",
        hiding: "적음",
        breaker: "꺼진 상태",
        weather: "폭풍우",
        items: "📦 3티어 최상급 탐색 장비 풀세트",
        strategy: "증거가 거의 나오지 않으므로 등대 나선 계단에서 유령의 헌팅 깜빡임 주기(팬텀/오니), 소금 피적 여부(레이스), 발소리 가속 패턴 등을 면밀히 관찰해야 합니다."
    }
];
